ezplatform_env_defaults:
  database_host: localhost
  database_name: "{{ site | underscore }}_{{ env }}"
  database_user: "{{ site | underscore }}"
  symfony_env: "{{ env }}"

site_env: "{{ ezplatform_env_defaults | combine(vault_ezplatform_env_defaults | default({}), project.env | default({}), vault_ezplatform_sites[site].env) }}"
site_hosts_canonical: "{{ item.value.site_hosts | map(attribute='canonical') | list }}"
site_hosts_redirects: "{{ item.value.site_hosts | selectattr('redirects', 'defined') | sum(attribute='redirects', start=[]) | list }}"
site_hosts: "{{ site_hosts_canonical | union(site_hosts_redirects) }}"
multisite_subdomains_wildcards: "{{ item.value.multisite.subdomains | default(false) | ternary( site_hosts_canonical | map('regex_replace', '^(www\\.)?(.*)$', '*.\\2') | list, [] ) }}"
ssl_enabled: "{{ item.value.ssl is defined and item.value.ssl.enabled | default(false) }}"
ssl_stapling_enabled: "{{ item.value.ssl is defined and item.value.ssl.stapling_enabled | default(true) }}"
sites_use_ssl: "{{ ezplatform_sites.values() | map(attribute='ssl') | selectattr('enabled') | list | count > 0 }}"
